In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from io import StringIO
%matplotlib inline

## Question 1

In [2]:
#pandas version
pd.__version__

'1.5.3'

####  Getting the data

In [10]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv'

req = requests.get(url)

if req.status_code == 200:
    df = pd.read_csv(StringIO(req.text))
    print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  


## Question 2

In [18]:
# how many columns in the dataset?
list(df.columns)

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income',
 'median_house_value',
 'ocean_proximity']

there are 10 columns

## Question 3

In [23]:
# which columns that hav null values?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


column total_bedrooms have missing values

## Question 4

In [29]:
# how many unique values does the ocean_proximity column have
df['ocean_proximity'].nunique()

5

## Question 5

In [45]:
# What's the average value of the median_house_value for the houses located near the bay?

df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean().round()

259212.0

## Question 6

In [49]:
# 1. Calculate the average of total_bedrooms column in the dataset.
df['total_bedrooms'].mean().round()

538.0

In [52]:
# 2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
df.fillna(df['total_bedrooms'].mean().round(), inplace=True)

In [53]:
# 3. Now, calculate the average of total_bedrooms again.
df['total_bedrooms'].mean().round()

538.0

In [84]:
# 4. Has it changed?

NO

## Question 7

In [64]:
# 1. Select all the options located on islands.
island = df[df['ocean_proximity'] == 'ISLAND']
island.count()

longitude             5
latitude              5
housing_median_age    5
total_rooms           5
total_bedrooms        5
population            5
households            5
median_income         5
median_house_value    5
ocean_proximity       5
dtype: int64

In [73]:
# 2. Select only columns housing_median_age, total_rooms, total_bedrooms.
island_second = island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
island_second

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [76]:
# 3. Get the underlying NumPy array. Let's call it X.
X = np.array(island_second)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [78]:
# 4. Compute matrix-matrix multiplication between the transpose of X and X. 
# To get the transpose, use X.T. Let's call the result XTX.
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [79]:
# 5. Compute the inverse of XTX.
inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [80]:
# 6. Create an array y with values [950, 1300, 800, 1000, 1300].
y = [950, 1300, 800, 1000, 1300]

In [82]:
# 7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
invXTX_XT = np.dot(inverse_XTX, X.T)

w = np.dot(invXTX_XT, y)

In [83]:
# 8. What's the value of the last element of w?
w

array([23.12330961, -1.48124183,  5.69922946])

5.6992

### Done!